/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.82
 * Generated at: 2017-11-23 05:14:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>扁平化bootstrap社交博客类型后台管理模板</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/demo.css\" rel=\"stylesheet\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("<!--[if IE]>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tli.remove_frame a {\r\n");
      out.write("\t\tpadding-top: 5px;\r\n");
      out.write("\t\tbackground-position: 0px -3px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.qrcode.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\tfunction fixHeight() {\r\n");
      out.write("\t\tvar headerHeight = $(\"#switcher\").height();\r\n");
      out.write("\t\t$(\"#iframe\").attr(\"height\", $(window).height()-54+ \"px\");\r\n");
      out.write("\t}\r\n");
      out.write("\t$(window).resize(function () {\r\n");
      out.write("\t\tfixHeight();\r\n");
      out.write("\t}).resize();\r\n");
      out.write("\r\n");
      out.write("\t$('.icon-monitor').addClass('active');\r\n");
      out.write("\r\n");
      out.write("\t$(\".icon-mobile-3\").click(function () {\r\n");
      out.write("\t\t$(\"#by\").css(\"overflow-y\", \"auto\");\r\n");
      out.write("\t\t$('#iframe-wrap').removeClass().addClass('mobile-width-3');\r\n");
      out.write("\t\t$('.icon-tablet,.icon-mobile-1,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\".icon-mobile-2\").click(function () {\r\n");
      out.write("\t\t$(\"#by\").css(\"overflow-y\", \"auto\");\r\n");
      out.write("\t\t$('#iframe-wrap').removeClass().addClass('mobile-width-2');\r\n");
      out.write("\t\t$('.icon-tablet,.icon-mobile-1,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\".icon-mobile-1\").click(function () {\r\n");
      out.write("\t\t$(\"#by\").css(\"overflow-y\", \"auto\");\r\n");
      out.write("\t\t$('#iframe-wrap').removeClass().addClass('mobile-width');\r\n");
      out.write("\t\t$('.icon-tablet,.icon-mobile,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\".icon-tablet\").click(function () {\r\n");
      out.write("\t\t$(\"#by\").css(\"overflow-y\", \"auto\");\r\n");
      out.write("\t\t$('#iframe-wrap').removeClass().addClass('tablet-width');\r\n");
      out.write("\t\t$('.icon-tablet,.icon-mobile-1,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\".icon-monitor\").click(function () {\r\n");
      out.write("\t\t$(\"#by\").css(\"overflow-y\", \"hidden\");\r\n");
      out.write("\t\t$('#iframe-wrap').removeClass().addClass('full-width');\r\n");
      out.write("\t\t$('.icon-tablet,.icon-mobile-1,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t\t$(this).addClass('active');\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function Responsive($a) {\r\n");
      out.write("\tif ($a == true) $(\"#Device\").css(\"opacity\", \"100\");\r\n");
      out.write("\tif ($a == false) $(\"#Device\").css(\"opacity\", \"0\");\r\n");
      out.write("\t$('#iframe-wrap').removeClass().addClass('full-width');\r\n");
      out.write("\t$('.icon-tablet,.icon-mobile-1,.icon-monitor,.icon-mobile-2,.icon-mobile-3').removeClass('active');\r\n");
      out.write("\t$(this).addClass('active');\r\n");
      out.write("\treturn false;\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"by\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"switcher\">\r\n");
      out.write("\t<div class=\"center\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("\t\t\t<div id=\"Device\">\r\n");
      out.write("\t\t\t\t<li class=\"device-monitor\"><a href=\"javascript:\"><div class=\"icon-monitor\"></div></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"device-mobile\"><a href=\"javascript:\"><div class=\"icon-tablet\"></div></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"device-mobile\"><a href=\"javascript:\"><div class=\"icon-mobile-1\"></div></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"device-mobile-2\"><a href=\"javascript:\"><div class=\"icon-mobile-2\"></div></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"device-mobile-3\"><a href=\"javascript:\"><div class=\"icon-mobile-3\"></div></a></li>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<li class=\"top2\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">手机二维码预览</a>\r\n");
      out.write("\t\t\t\t<div class=\"vm\">\r\n");
      out.write("\t\t\t\t\t<div id=\"output\"></div>\r\n");
      out.write("\t\t\t\t\t<p style=\"color:#808080;margin:10px 0 0 0;\">扫一扫，直接在手机上打开</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t -->\r\n");
      out.write("\t\t\t<li class=\"logoTop\"><a href=\"/pins/25299.html\">大型预制构件预应力管理系统</a></li>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery('#output').qrcode({width:150,height: 150,text: window.location.href});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!--<li class=\"remove_frame\"><a href=\"http://www.17sucai.com/preview/2/2017-06-28/cleanzone/index.html\" title=\"移除框架\"></a></li>-->\r\n");
      out.write("\t\t\t<li class=\"remove_frame\"><a href=\"/WEB-INF/jsp/mainPage2\" title=\"移除框架\"></a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"iframe-wrap\">\r\n");
      out.write("\t<!--<iframe id=\"iframe\" src=\"http://www.17sucai.com/preview/2/2017-06-28/cleanzone/index.html\" frameborder=\"0\"  width=\"100%\"></iframe>-->\r\n");
      out.write("\t<li class=\"remove_frame\"><a href=\"/WEB-INF/jsp/mainPage2\" title=\"移除框架\"></a></li>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
